#!/bin/bash

# chkconfig: 345 85 15

# description: DEV WebSite GateWay .

# processname: devCmdServerDeamon

# pidfile: /var/run/devCmdServerDeamon.pid
# Source function library.
. /etc/rc.d/init.d/functions

prog=devCmdServerDeamon
devcmdserver=/usr/share/nginx/dev/cmdserver/GateWay.php
pidfile=/var/run/devCmdServerDeamon.pid
php=/bin/php
OPTIONS="1 off $pidfile"

HTTPD_LANG=${HTTPD_LANG-"C"}
INITLOG_ARGS=""

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}



usage(){
  echo " usage:$0 {start|stop|restart} "
}
start(){
        echo -n $"Starting $prog: "
        LANG=$HTTPD_LANG daemon --pidfile=${pidfile}  php ${devcmdserver}  $OPTIONS >/dev/null 2>&1
        RETVAL=$?
        echo
        [ $RETVAL = 0 ]
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog: "
        killproc -p ${pidfile} -d ${STOP_TIMEOUT}  php ${devcmdserver}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}



restart(){
  stop
  start
}

case $1 in
  start)
     start
     ;;
  stop)
     stop
     ;;
  restart)
     restart
     ;;
  *)
     usage
     ;;
esac